theme: jekyll-theme-minimal
title: 3DFax's homepage
description:  
_  _ ____ _    _    ____    _ _ _ ____ ____ _    ___  
|__| |___ |    |    |  |    | | | |  | |__/ |    |  \ 
|  | |___ |___ |___ |__|    |_|_| |__| |  \ |___ |__/ 
